level.count=4

level.1.rows=20
level.1.cols=28
level.1.foodCount=3
level.1.obstacleCount=18
level.1.robotCount=2
level.1.winLength=5
level.1.tickMillis=200

level.2.rows=20
level.2.cols=28
level.2.foodCount=4
level.2.obstacleCount=18
level.2.robotCount=2
level.2.winLength=10
level.2.tickMillis=150

level.3.rows=20
level.3.cols=28
level.3.foodCount=6
level.3.obstacleCount=18
level.3.robotCount=2
level.3.winLength=15
level.3.tickMillis=100

level.4.rows=20
level.4.cols=28
level.4.foodCount=5
level.4.obstacleCount=18
level.4.robotCount=2
level.4.winLength=20
level.4.tickMillis=70
